-- Asegurar que cartera_propiedades tiene TODAS las columnas que usa el formulario
-- Usa IF NOT EXISTS en cada columna para que sea idempotente
ALTER TABLE cartera_propiedades
  -- Identificación
  ADD COLUMN IF NOT EXISTS codigo               text,
  -- Precio
  ADD COLUMN IF NOT EXISTS expensas             numeric(12,2),
  ADD COLUMN IF NOT EXISTS moneda_expensas      text DEFAULT 'ARS',
  ADD COLUMN IF NOT EXISTS ocultar_precio       boolean DEFAULT false,
  -- Visibilidad
  ADD COLUMN IF NOT EXISTS ocultar_de_redes     boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS ocultar_web          boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS publicada_web        boolean DEFAULT false,
  -- Honorarios
  ADD COLUMN IF NOT EXISTS honorario_compartir  text,
  ADD COLUMN IF NOT EXISTS honorario_propietario numeric(5,2),
  ADD COLUMN IF NOT EXISTS honorario_comprador  numeric(5,2),
  -- Ubicación extendida
  ADD COLUMN IF NOT EXISTS direccion_orientativa text,
  ADD COLUMN IF NOT EXISTS codigo_postal        text,
  ADD COLUMN IF NOT EXISTS sector               text,
  ADD COLUMN IF NOT EXISTS manzana              text,
  ADD COLUMN IF NOT EXISTS ocultar_ubicacion    boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS latitud              numeric(10,7),
  ADD COLUMN IF NOT EXISTS longitud             numeric(10,7),
  -- Características de la unidad
  ADD COLUMN IF NOT EXISTS banos_servicio       integer,
  ADD COLUMN IF NOT EXISTS estacionamientos     integer,
  ADD COLUMN IF NOT EXISTS anio_construccion    integer,
  ADD COLUMN IF NOT EXISTS piso                 text,
  ADD COLUMN IF NOT EXISTS numero_unidad        text,
  ADD COLUMN IF NOT EXISTS numero_torre         text,
  ADD COLUMN IF NOT EXISTS pisos_edificio       integer,
  ADD COLUMN IF NOT EXISTS departamentos_por_piso integer,
  ADD COLUMN IF NOT EXISTS bauleras             integer,
  ADD COLUMN IF NOT EXISTS disposicion          text,
  ADD COLUMN IF NOT EXISTS orientacion          text,
  ADD COLUMN IF NOT EXISTS tipo_departamento    text,
  ADD COLUMN IF NOT EXISTS luminosidad          text,
  ADD COLUMN IF NOT EXISTS condicion            text,
  ADD COLUMN IF NOT EXISTS antiguedad           text,
  -- Superficies extendidas
  ADD COLUMN IF NOT EXISTS sup_semicubierta     numeric(10,2),
  ADD COLUMN IF NOT EXISTS sup_descubierta      numeric(10,2),
  ADD COLUMN IF NOT EXISTS sup_exclusiva        numeric(10,2),
  ADD COLUMN IF NOT EXISTS sup_espacios_comunes numeric(10,2),
  ADD COLUMN IF NOT EXISTS sup_patio_terraza    numeric(10,2),
  ADD COLUMN IF NOT EXISTS sup_balcon           numeric(10,2),
  ADD COLUMN IF NOT EXISTS metros_frente        numeric(10,2),
  ADD COLUMN IF NOT EXISTS metros_fondo         numeric(10,2),
  -- Características booleanas
  ADD COLUMN IF NOT EXISTS apto_credito         boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS con_cochera          boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amoblado             boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS habitada             boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS acepta_permuta       boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS acepta_mascotas      boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS barrio_cerrado       boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS uso_comercial        boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS energia_solar        boolean DEFAULT false,
  -- Descripciones adicionales
  ADD COLUMN IF NOT EXISTS descripcion_privada  text,
  ADD COLUMN IF NOT EXISTS comentarios_colegas  text,
  ADD COLUMN IF NOT EXISTS aviso_legal          text,
  ADD COLUMN IF NOT EXISTS video_url            text,
  -- Fotos y multimedia
  ADD COLUMN IF NOT EXISTS fotos                text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS amenities            text[] DEFAULT '{}',
  -- Ambientes
  ADD COLUMN IF NOT EXISTS amb_balcon           boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_terraza          boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_patio            boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_jardin           boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_parrilla         boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_living           boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_comedor          boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_comedor_diario   boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_cocina           boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_estudio          boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_vestidor         boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_lavadero         boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_sotano           boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_roof_garden      boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_playroom         boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_dep_servicio     boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amb_dorm_suite       boolean DEFAULT false,
  -- Comodidades
  ADD COLUMN IF NOT EXISTS com_pileta           boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_gimnasio         boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_sum              boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_salon_fiestas    boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_sala_juegos      boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_solarium         boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_hidromasaje      boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_jacuzzi          boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_ascensor         boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_seguridad        boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_internet         boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_aire_acondicionado boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_calefaccion      boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_cowork           boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_cancha_tenis     boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_cancha_paddle    boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_cancha_futbol    boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_lavanderia       boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_juegos_infantiles boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_estac_visitantes boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_quincho          boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS com_grupo_electrogeno boolean DEFAULT false;
